#!/usr/bin/env bash

declare -a patches=(\
"emojione-2.2.7" \
"jquery-textcomplete" \
"json-prune" \
"json3" \
"webpack" \
"xregexp" \
)

for i in "${patches[@]}"
do
    echo "Processing patch for ${i}"
    patch -p0 -N --dry-run --silent < "patches/${i}.patch" 2>/dev/null; \
    if [ $? -eq 0 ]; \
    then \
        patch -p0 -N < "patches/${i}.patch"; \
    fi
done
