#
# Copyright (C) 2017 ZeXtras S.r.l.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation, version 2 of
# the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License.
# If not, see <http://www.gnu.org/licenses/>.
#

define(
  [
    "require",
    "exports"
  ],
  (
    require,
    exports
  ) ->
    "use strict"
    
    class ZxErrorCode

      @_msgs: {}

      @UNKNOWN_ERROR: "UNKNOWN_ERROR"
      @_msgs.UNKNOWN_ERROR = "Unknown Error"
      @UNABLE_TO_PARSE_JSON_STRING: "UNABLE_TO_PARSE_JSON_STRING"
      @_msgs.UNABLE_TO_PARSE_JSON_STRING = "Cannot parse json string {json}: {error}"
      @NO_SUCH_CHAT_SESSION: "NO_SUCH_CHAT_SESSION"
      @_msgs.NO_SUCH_CHAT_SESSION = "ZxChat session {session_id} not found"
      @UNABLE_TO_FIND_COMMAND_FOR_EVENT: "UNABLE_TO_FIND_COMMAND_FOR_EVENT"
      @_msgs.UNABLE_TO_FIND_COMMAND_FOR_EVENT = "Unable to find command for command id '{commandId}'"
      @ZM_CSFE_EXCEPTION: "ZM_CSFE_EXCEPTION"
      @_msgs.ZM_CSFE_EXCEPTION = "ZmCsfeException: {code}\nMessage: {msg}"
      @CHAT_CONCURRENT_PING: "CHAT_CONCURRENT_PING"
      @_msgs.CHAT_CONCURRENT_PING = "Multiple concurrent pings, older ping has been killed"
      @UNABLE_TO_ENCODE_EVENT_OBJECT: "UNABLE_TO_ENCODE_EVENT_OBJECT"
      @_msgs.UNABLE_TO_ENCODE_EVENT_OBJECT = "Unable to encode the event object:\n{object}"
      @UNABLE_TO_SEND_EVENT_OBJECT: "UNABLE_TO_SEND_EVENT_OBJECT"
      @_msgs.UNABLE_TO_SEND_EVENT_OBJECT = "Error on sending event object:\n{object}"
      @UNABLE_TO_DECODE_EVENT_OBJECT: "UNABLE_TO_DECODE_EVENT_OBJECT"
      @_msgs.UNABLE_TO_DECODE_EVENT_OBJECT = "Unable to decode the event object:\n{object}\noriginated by the event:\n{originEvent}"
      @UNABLE_TO_HANDLE_EVENT_ERROR: "UNABLE_TO_HANDLE_EVENT_ERROR"
      @_msgs.UNABLE_TO_HANDLE_EVENT_ERROR = "Error on handling event:\n{event}"
      @DETECTED_502: "DETECTED_502"
      @_msgs.DETECTED_502 = "Proxy misconfiguration detected, please contact your administrator:\n{detail}"
      @DELEGATED_OR_RESOURCES_NOT_ALLOWED_TO_CHAT: "DELEGATED_OR_RESOURCES_NOT_ALLOWED_TO_CHAT"
      @_msgs.DELEGATED_OR_RESOURCES_NOT_ALLOWED_TO_CHAT = "ZxChat is disabled for delegated access or resource accounts"
      @AJX_EXCEPTION: "AJX_EXCEPTION"
      @_msgs.AJX_EXCEPTION = "AjxException: {details}"
      @INVALID_CHAT_ACCOUNT: "INVALID_CHAT_ACCOUNT"
      @_msgs.INVALID_CHAT_ACCOUNT = "{account} is not a vaild account for the chat server"

      @GENERIC_ERROR: "GENERIC_ERROR"
      @_msgs.GENERIC_ERROR = "Generic Error: {details}"
      @UNABLE_TO_READ_WRITE_FILE: "UNABLE_TO_READ_WRITE_FILE"
      @_msgs.UNABLE_TO_READ_WRITE_FILE = "Can not read/write file: {filename}"
      @UNABLE_TO_FIND_HANDLER: "UNABLE_TO_FIND_HANDLER"
      @_msgs.UNABLE_TO_FIND_HANDLER = "Unable to find handler {name}"
      @UNKNOWN_ACTION: "UNKNOWN_ACTION"
      @_msgs.UNKNOWN_ACTION = "Unknown action: {action}"
      @INVALID_ACE_STRING: "INVALID_ACE_STRING"
      @_msgs.INVALID_ACE_STRING = "Invalid aceString: {aceString}"
      @UNABLE_TO_READ_LICENSE_FILE: "UNABLE_TO_READ_LICENSE_FILE"
      @_msgs.UNABLE_TO_READ_LICENSE_FILE = "Unable to read license file"
      @UNABLE_TO_READ_LOCAL_LOG_FILES: "UNABLE_TO_READ_LOCAL_LOG_FILES"
      @_msgs.UNABLE_TO_READ_LOCAL_LOG_FILES = "Unable to read local log files"
      @UNABLE_TO_OBTAIN_DB_CONNECTION: "UNABLE_TO_OBTAIN_DB_CONNECTION"
      @_msgs.UNABLE_TO_OBTAIN_DB_CONNECTION = "Unable to obtain database connection"
      @UNABLE_TO_SAVE_METADATA_ON_MAILBOX: "UNABLE_TO_SAVE_METADATA_ON_MAILBOX"
      @_msgs.UNABLE_TO_SAVE_METADATA_ON_MAILBOX = "Unable to save metadata on mailbox {mboxID} size: {size}"
      @INVALID_ADMIN_LOG_PATH_IS_NOT_DIRECTORY: "INVALID_ADMIN_LOG_PATH_IS_NOT_DIRECTORY"
      @_msgs.INVALID_ADMIN_LOG_PATH_IS_NOT_DIRECTORY = "Invalid path for admin log: {path} is not a directory"
      @UNABLE_TO_COMPLETE_OPERATION_PATH_MUST_BE_READABLE: "UNABLE_TO_COMPLETE_OPERATION_PATH_MUST_BE_READABLE"
      @_msgs.UNABLE_TO_COMPLETE_OPERATION_PATH_MUST_BE_READABLE = "Unable to complete the operation: the new log path must be readable and writable by the 'zimbra' user"
      @PATH_DOES_NOT_EXISTS_AND_CANNOT_BE_CREATED: "PATH_DOES_NOT_EXISTS_AND_CANNOT_BE_CREATED"
      @_msgs.PATH_DOES_NOT_EXISTS_AND_CANNOT_BE_CREATED = "Directory {path} doesn't exist and could not be created"
      @PATHS_MUST_DIFFER: "PATHS_MUST_DIFFER"
      @_msgs.PATHS_MUST_DIFFER = "The new path must be different from the old one"
      @INVALID_VALUE_FOR_PROPERTY: "INVALID_VALUE_FOR_PROPERTY"
      @_msgs.INVALID_VALUE_FOR_PROPERTY = "Invalid value {value} for property {key}"
      @UNABLE_TO_ACCESS_DIRECTORY: "UNABLE_TO_ACCESS_DIRECTORY"
      @_msgs.UNABLE_TO_ACCESS_DIRECTORY = "Cannot access directory {directory}"
      @DIRECTORY_NOT_EMPTY: "DIRECTORY_NOT_EMPTY"
      @_msgs.DIRECTORY_NOT_EMPTY = "Directory {directory} is not empty"
      @UNKNOWN_EXCEPTION: "UNKNOWN_EXCEPTION"
      @_msgs.UNKNOWN_EXCEPTION = "Unknown Exception {exception}"
      @GENERIC_OPERATION_ERROR: "GENERIC_OPERATION_ERROR"
      @_msgs.GENERIC_OPERATION_ERROR = "{details}"
      @OPERATION_ERROR: "OPERATION_ERROR"
      @_msgs.OPERATION_ERROR = "[{opName}] {details}"
      @INVALID_LICENSE: "INVALID_LICENSE"
      @_msgs.INVALID_LICENSE = "Invalid license: {cause} not valid"
      @UNABLE_TO_CREATE_LICENSE: "UNABLE_TO_CREATE_LICENSE"
      @_msgs.UNABLE_TO_CREATE_LICENSE = "Unable to create license"
      @INVALID_TARGET_TYPE: "INVALID_TARGET_TYPE"
      @_msgs.INVALID_TARGET_TYPE = "Invalid target type {type}"
      @INVALID_GRANTEE_TYPE: "INVALID_GRANTEE_TYPE"
      @_msgs.INVALID_GRANTEE_TYPE = "Invalid grantee type {type}"
      @INVALID_RIGHT_MODIFIER: "INVALID_RIGHT_MODIFIER"
      @_msgs.INVALID_RIGHT_MODIFIER = "Invalid right modifier {modifier}"
      @REPORT_ALREADY_BEING_GENERATED: "REPORT_ALREADY_BEING_GENERATED"
      @_msgs.REPORT_ALREADY_BEING_GENERATED = "A report is already being generated. No concurrent operations of this type are allowed."
      @INVALID_SERVER_CONFIG: "INVALID_SERVER_CONFIG"
      @_msgs.INVALID_SERVER_CONFIG = "Invalid server config"
      @UNABLE_TO_VERIFY_LICENSE: "UNABLE_TO_VERIFY_LICENSE"
      @_msgs.UNABLE_TO_VERIFY_LICENSE = "Invalid License: unable to verify license"
      @LICENSE_NOT_LONGER_VALID: "LICENSE_NOT_LONGER_VALID"
      @_msgs.LICENSE_NOT_LONGER_VALID = "License is no longer valid (order id {orderID}), contact the ZeXtras sales team."
      @INVALID_ZX_VERSION_FOR_LICENSE: "INVALID_ZX_VERSION_FOR_LICENSE"
      @_msgs.INVALID_ZX_VERSION_FOR_LICENSE = "License is not valid for this version ({currentVersion}) you need at least {requiredVersion}"
      @MISSING_PARAMETERS: "MISSING_PARAMETERS"
      @_msgs.MISSING_PARAMETERS = "Missing parameters"
      @HSM_ROLLBACK_ERROR: "HSM_ROLLBACK_ERROR"
      @_msgs.HSM_ROLLBACK_ERROR = "Error during the rollback: {message}. {size} items can be inconsistent. Please run a zmblobchk on the primary volume."
      @UNABLE_TO_START_CONSOLE_ON_MODULE: "UNABLE_TO_START_CONSOLE_ON_MODULE"
      @_msgs.UNABLE_TO_START_CONSOLE_ON_MODULE = "Unable to start console mode on module {module}"
      @UNABLE_TO_START_SERVER_MODULE: "UNABLE_TO_START_SERVER_MODULE"
      @_msgs.UNABLE_TO_START_SERVER_MODULE = "Unable to start server mode on module {module}"
      @UNABLE_TO_STOP_MODULE: "UNABLE_TO_STOP_MODULE"
      @_msgs.UNABLE_TO_STOP_MODULE = "Unable to stop module {module}"
      @READING_SERVER_BACKUP_ERROR: "READING_SERVER_BACKUP_ERROR"
      @_msgs.READING_SERVER_BACKUP_ERROR = "Exception when reading server backup"
      @UNABLE_TO_READ_BACKUP_DIRECTORY: "UNABLE_TO_READ_BACKUP_DIRECTORY"
      @_msgs.UNABLE_TO_READ_BACKUP_DIRECTORY = "Unable to read server backup directory"
      @UNABLE_TO_UPDATE_STATS: "UNABLE_TO_UPDATE_STATS"
      @_msgs.UNABLE_TO_UPDATE_STATS = "Can't update stats"
      @UNABLE_TO_FIND_BACKUP_IN_PATH: "UNABLE_TO_FIND_BACKUP_IN_PATH"
      @_msgs.UNABLE_TO_FIND_BACKUP_IN_PATH = "No account found: {account} in path: {path}"
      @INVALID_RESPONSE_SERVER: "INVALID_RESPONSE_SERVER"
      @_msgs.INVALID_RESPONSE_SERVER = "Invalid server response from {server}"
      @MANDATORY_PARAMETER_MISSING: "MANDATORY_PARAMETER_MISSING"
      @_msgs.MANDATORY_PARAMETER_MISSING = "Mandatory parameters missing"
      @UNKNOWN_TYPE_ERROR: "UNKNOWN_TYPE_ERROR"
      @_msgs.UNKNOWN_TYPE_ERROR = "Unknown type {type}"
      @INVALID_DATE: "INVALID_DATE"
      @_msgs.INVALID_DATE = "Date not valid: {args} [{details}]"
      @INVALID_SYNC_DATE: "INVALID_SYNC_DATE"
      @_msgs.INVALID_SYNC_DATE = "Date not valid: {args} [{details}]"
      @INVALID_DATE_FORMAT: "INVALID_DATE_FORMAT"
      @_msgs.INVALID_DATE_FORMAT = "Invalid date: '{dateStr}'. Must be in the format mm/yyyy."
      @INVALID_ARGUMENT_TYPE: "INVALID_ARGUMENT_TYPE"
      @_msgs.INVALID_ARGUMENT_TYPE = "Invalid argument '{argument}' for parameter of type '{type}'"
      @MISSING_VALUE_FOR_PARAMETER: "MISSING_VALUE_FOR_PARAMETER"
      @_msgs.MISSING_VALUE_FOR_PARAMETER = "Missing value for parameter '{argument}'"
      @INVALID_VOLUME_TYPE: "INVALID_VOLUME_TYPE"
      @_msgs.INVALID_VOLUME_TYPE = "Invalid Volume type: Volume type must be primary, secondary or index"
      @TOO_MANY_ARGUMENTS: "TOO_MANY_ARGUMENTS"
      @_msgs.TOO_MANY_ARGUMENTS = "Error: too many arguments, or optional argument without parameter name in front of it"
      @OPERATION_NOT_YET_SUPPORTED: "OPERATION_NOT_YET_SUPPORTED"
      @_msgs.OPERATION_NOT_YET_SUPPORTED = "Operation {operation} not yet supported"
      @INVALID_RECURRENCE_TYPE: "INVALID_RECURRENCE_TYPE"
      @_msgs.INVALID_RECURRENCE_TYPE = "Invalid Recurrence Type {type}"
      @UNABLE_TO_PARSE_SEARCH_REQUEST: "UNABLE_TO_PARSE_SEARCH_REQUEST"
      @_msgs.UNABLE_TO_PARSE_SEARCH_REQUEST = "Unable to parse Search Request"
      @INVALID_STATUS: "INVALID_STATUS"
      @_msgs.INVALID_STATUS = "Invalid Status: {status}"
      @INVALID_SYNC_KEY_LENGTH: "INVALID_SYNC_KEY_LENGTH"
      @_msgs.INVALID_SYNC_KEY_LENGTH = "Invalid SyncKey Length: {length}"
      @INVALID_SERVER_ID: "INVALID_SERVER_ID"
      @_msgs.INVALID_SERVER_ID = "Invalid ServerId({serverID})"
      @INVALID_RANGE: "INVALID_RANGE"
      @_msgs.INVALID_RANGE = "Invalid Range: {range}"
      @INVALID_NUMBER: "INVALID_NUMBER"
      @_msgs.INVALID_NUMBER = "Invalid Number: {error}"
      @INVALID_FLAG_STATUS_VALUE: "INVALID_FLAG_STATUS_VALUE"
      @_msgs.INVALID_FLAG_STATUS_VALUE = "Invalid FlagStatus value of {value}"
      @UNKNOWN_SYNC_STATE: "UNKNOWN_SYNC_STATE"
      @_msgs.UNKNOWN_SYNC_STATE = "Client {id} sent an unknown SyncState: {state}"
      @CLIENT_OUT_OF_SYNC: "CLIENT_OUT_OF_SYNC"
      @_msgs.CLIENT_OUT_OF_SYNC = "Client {id} out of sync"
      @INVALID_COMMAND: "INVALID_COMMAND"
      @_msgs.INVALID_COMMAND = "Invalid command: {command}"
      @INVALID_DOCUMENT: "INVALID_DOCUMENT"
      @_msgs.INVALID_DOCUMENT = "Invalid document: {document}"
      @UNABLE_TO_FIND_CONFIG_REVISION: "UNABLE_TO_FIND_CONFIG_REVISION"
      @_msgs.UNABLE_TO_FIND_CONFIG_REVISION = "Configuration {config} has no revision code, resetting config"
      @UNABLE_TO_FIND_KEY_ON_MAILBOX_METADATA: "UNABLE_TO_FIND_KEY_ON_MAILBOX_METADATA"
      @_msgs.UNABLE_TO_FIND_KEY_ON_MAILBOX_METADATA = "Cannot find key {key} on mailbox {mbox} metadata: {error}"
      @UNABLE_TO_RETRIEVE_ACCOUNT_FOR_MAILBOX: "UNABLE_TO_RETRIEVE_ACCOUNT_FOR_MAILBOX"
      @_msgs.UNABLE_TO_RETRIEVE_ACCOUNT_FOR_MAILBOX = "Unable to retrieve account for mailbox {mbox}"
      @RIETRIEVING_KEY_FOR_MBOX_ERROR: "RIETRIEVING_KEY_FOR_MBOX_ERROR"
      @_msgs.RIETRIEVING_KEY_FOR_MBOX_ERROR = "Error retrieving key {key} on mailbox {mboxID}: {error}"
      @UNABLE_TO_DELIVER_MESSAGE: "UNABLE_TO_DELIVER_MESSAGE"
      @_msgs.UNABLE_TO_DELIVER_MESSAGE = "Unable to deliver message"
      @UNABLE_TO_REGISTER_DATABASE_DRIVER: "UNABLE_TO_REGISTER_DATABASE_DRIVER"
      @_msgs.UNABLE_TO_REGISTER_DATABASE_DRIVER = "Unable to register Database Driver"
      @INVALID_RECURRENCE_FREQUENCE: "INVALID_RECURRENCE_FREQUENCE"
      @_msgs.INVALID_RECURRENCE_FREQUENCE = "Invalid recurrence frequency"
      @REMOTE_EXCEPTION_ERROR: "REMOTE_EXCEPTION_ERROR"
      @_msgs.REMOTE_EXCEPTION_ERROR = "Remote Exception: {exception}/{error}"
      @CANNOT_RETRIEVE_OPERATION_NAME: "CANNOT_RETRIEVE_OPERATION_NAME"
      @_msgs.CANNOT_RETRIEVE_OPERATION_NAME = "Cannot retrieve operation name"
      @CANNOT_COMMUNICATE_WITH_SERVER: "CANNOT_COMMUNICATE_WITH_SERVER"
      @_msgs.CANNOT_COMMUNICATE_WITH_SERVER = "Unable to communicate with server"
      @EMPTY_STRING: "EMPTY_STRING"
      @_msgs.EMPTY_STRING = "Empty String"
      @INVALID_BOOLEAN: "INVALID_BOOLEAN"
      @_msgs.INVALID_BOOLEAN = "Invalid Boolean"
      @MISSING_PARAMETER: "MISSING_PARAMETER"
      @_msgs.MISSING_PARAMETER = "Parameter {parameter} not found"
      @ACCOUNT_ON_ANOTHER_SERVER: "ACCOUNT_ON_ANOTHER_SERVER"
      @_msgs.ACCOUNT_ON_ANOTHER_SERVER = "The specified account belongs to another server: {server}"
      @CONNECTION_EXCEPTION: "CONNECTION_EXCEPTION"
      @_msgs.CONNECTION_EXCEPTION = "Connection Exception"
      @INVALID_EOS: "INVALID_EOS"
      @_msgs.INVALID_EOS = "Invalid End Of Stream: {packet}"
      @INVALID_STREAM_ENCODING: "INVALID_STREAM_ENCODING"
      @_msgs.INVALID_STREAM_ENCODING = "Invalid stream with encoding {encoding}"
      @INVALID_JSON: "INVALID_JSON"
      @_msgs.INVALID_JSON = "Invalid JSON"
      @UNABLE_TO_COMMUNICATE_WITH_SERVER: "UNABLE_TO_COMMUNICATE_WITH_SERVER"
      @_msgs.UNABLE_TO_COMMUNICATE_WITH_SERVER = "Unable to communicate with server"
      @VERSION_DIFFERS: "VERSION_DIFFERS"
      @_msgs.VERSION_DIFFERS = "Version differs: {version} ({current})"
      @INVALID_ZE_PACKET_HEADER: "INVALID_ZE_PACKET_HEADER"
      @_msgs.INVALID_ZE_PACKET_HEADER = "Invalid JSON Header: read bytes: {header}/{length}"
      @IO_READING_ERROR: "IO_READING_ERROR"
      @_msgs.IO_READING_ERROR = "IO error reading the blob item. {details}"
      @UNABLE_TO_LOAD_SERVER_SCRIPT: "UNABLE_TO_LOAD_SERVER_SCRIPT"
      @_msgs.UNABLE_TO_LOAD_SERVER_SCRIPT = "Cannot load server script: {script}"
      @KEY_NOT_FOUND: "KEY_NOT_FOUND"
      @_msgs.KEY_NOT_FOUND = "Key Not Found: {key}"
      @INVALID_TARGET_SERVER_FIELD: "INVALID_TARGET_SERVER_FIELD"
      @_msgs.INVALID_TARGET_SERVER_FIELD = "Invalid targetServer field"
      @MODULE_NOT_FOUND: "MODULE_NOT_FOUND"
      @_msgs.MODULE_NOT_FOUND = "Module not found: {details}"
      @UNABLE_TO_CREATE_TEMP_ITEM: "UNABLE_TO_CREATE_TEMP_ITEM"
      @_msgs.UNABLE_TO_CREATE_TEMP_ITEM = "Unable to create temp item"
      @PARTIAL_PROVISIONING_NOT_ALLOWED: "PARTIAL_PROVISIONING_NOT_ALLOWED"
      @_msgs.PARTIAL_PROVISIONING_NOT_ALLOWED = "Partial provisioning not allowed"
      @DEVICE_SUSPENDED_BY_USER: "DEVICE_SUSPENDED_BY_USER"
      @_msgs.DEVICE_SUSPENDED_BY_USER = "This device is been suspended by user"
      @NO_DOMAIN_SPECIFIED: "NO_DOMAIN_SPECIFIED"
      @_msgs.NO_DOMAIN_SPECIFIED = "No domain specified"
      @SERVER_NOT_LICENSED_FOR_MOBILE_USE: "SERVER_NOT_LICENSED_FOR_MOBILE_USE"
      @_msgs.SERVER_NOT_LICENSED_FOR_MOBILE_USE = "The server is not licensed for mobile use"
      @MOBILE_DISABLED_BY_USER: "MOBILE_DISABLED_BY_USER"
      @_msgs.MOBILE_DISABLED_BY_USER = "The mobile module is disabled by user"
      @ACCOUNT_NOT_ENABLED_FOR_MOBILE: "ACCOUNT_NOT_ENABLED_FOR_MOBILE"
      @_msgs.ACCOUNT_NOT_ENABLED_FOR_MOBILE = "The specified account is not enabled for mobile use"
      @MOBILE_NOT_ALLOWED_FOR_ACCOUNT_TYPE: "MOBILE_NOT_ALLOWED_FOR_ACCOUNT_TYPE"
      @_msgs.MOBILE_NOT_ALLOWED_FOR_ACCOUNT_TYPE = "Mobile synchronization is not allowed for \"{type}\" mailboxes"
      @INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR"
      @_msgs.INTERNAL_SERVER_ERROR = "Internal server error {code}"
      @INVALID_AUTH_PROVIDED: "INVALID_AUTH_PROVIDED"
      @_msgs.INVALID_AUTH_PROVIDED = "Invalid authorization provided"
      @NO_AUTH_PROVIDED: "NO_AUTH_PROVIDED"
      @_msgs.NO_AUTH_PROVIDED = "No Authorization provided"
      @PROVISIONING_EXCEPTION: "PROVISIONING_EXCEPTION"
      @_msgs.PROVISIONING_EXCEPTION = "Provisioning Exception"
      @INVALID_CREDENTIALS: "INVALID_CREDENTIALS"
      @_msgs.INVALID_CREDENTIALS = "Invalid credentials"
      @ACCOUNT_IN_MAINTENANCE_MODE: "ACCOUNT_IN_MAINTENANCE_MODE"
      @_msgs.ACCOUNT_IN_MAINTENANCE_MODE = "Account in Maintenance Mode"
      @ACCOUNT_PASSWORD_MUST_CHANGE: "ACCOUNT_PASSWORD_MUST_CHANGE"
      @_msgs.ACCOUNT_PASSWORD_MUST_CHANGE = "Account Password Must Change"
      @CONTEXT_NOT_AUTHENTICATED: "CONTEXT_NOT_AUTHENTICATED"
      @_msgs.CONTEXT_NOT_AUTHENTICATED = "{context}"
      @UNABLE_TO_SANITIZE_FOLDER_NAME: "UNABLE_TO_SANITIZE_FOLDER_NAME"
      @_msgs.UNABLE_TO_SANITIZE_FOLDER_NAME = "Cannot sanitize folder name: {name}"
      @UNABLE_TO_RETRIEVE_ACCOUNT_FROM_ID: "UNABLE_TO_RETRIEVE_ACCOUNT_FROM_ID"
      @_msgs.UNABLE_TO_RETRIEVE_ACCOUNT_FROM_ID = "Error retrieving account from id: {details}"
      @USER_DOES_NOT_EXISTS: "USER_DOES_NOT_EXISTS"
      @_msgs.USER_DOES_NOT_EXISTS = "User {user} does not exists"
      @INVALID_ACCOUNT_STATUS: "INVALID_ACCOUNT_STATUS"
      @_msgs.INVALID_ACCOUNT_STATUS = "User {user} account status is {status}"
      @ITEM_ID_MUST_BE_INTEGER: "ITEM_ID_MUST_BE_INTEGER"
      @_msgs.ITEM_ID_MUST_BE_INTEGER = "Item ID must be an integer"
      @INVALID_SEARCH_FILTER: "INVALID_SEARCH_FILTER"
      @_msgs.INVALID_SEARCH_FILTER = "Invalid search filter '{filter}'. Must be either 'all', 'deleted' or 'not_deleted'"
      @INVALID_ITEM_TYPE: "INVALID_ITEM_TYPE"
      @_msgs.INVALID_ITEM_TYPE = "Invalid type '{type}'. Must be either 'message', 'contact', 'folder' or 'all'"
      @SEARCH_STRING_TOO_SHORT: "SEARCH_STRING_TOO_SHORT"
      @_msgs.SEARCH_STRING_TOO_SHORT = "Search string '{searchString}' is too short. It must be at least 5 characters long"
      @PATH_DOES_NOT_EXISTS_OR_IS_NOT_A_DIRECTORY: "PATH_DOES_NOT_EXISTS_OR_IS_NOT_A_DIRECTORY"
      @_msgs.PATH_DOES_NOT_EXISTS_OR_IS_NOT_A_DIRECTORY = "Path {path} either doesn't exist or is not a directory"
      @UNABLE_TO_SAVE_CONFIGURATION_ON_MAILBOX: "UNABLE_TO_SAVE_CONFIGURATION_ON_MAILBOX"
      @_msgs.UNABLE_TO_SAVE_CONFIGURATION_ON_MAILBOX = "Unable to save configuration to mailbox {mboxID}"
      @UNABLE_TO_CONNECT_TO_SERVER: "UNABLE_TO_CONNECT_TO_SERVER"
      @_msgs.UNABLE_TO_CONNECT_TO_SERVER = "Unable to connect to server: {host}"
      @UNABLE_TO_PROXY_REQUEST: "UNABLE_TO_PROXY_REQUEST"
      @_msgs.UNABLE_TO_PROXY_REQUEST = "Unable to proxy request {module}/{action}"
      @XPATH_GENERIC_ERROR: "XPATH_GENERIC_ERROR"
      @_msgs.XPATH_GENERIC_ERROR = "Error during XPath query"
      @UNABLE_TO_OPEN_FILE: "UNABLE_TO_OPEN_FILE"
      @_msgs.UNABLE_TO_OPEN_FILE = "Cannot open file: {file}"
      @UNABLE_TO_READ_FILE: "UNABLE_TO_READ_FILE"
      @_msgs.UNABLE_TO_READ_FILE = "Error reading file: {file}"
      @UNABLE_TO_READ_BACKUP_FILE: "UNABLE_TO_READ_BACKUP_FILE"
      @_msgs.UNABLE_TO_READ_BACKUP_FILE = "Unable to read backup file: {file}"
      @UNABLE_TO_SERIALIZE_SYNC_STATE: "UNABLE_TO_SERIALIZE_SYNC_STATE"
      @_msgs.UNABLE_TO_SERIALIZE_SYNC_STATE = "Unable to serialize sync state for mailbox {mboxID}"
      @UNABLE_TO_FIND_VOLUME: "UNABLE_TO_FIND_VOLUME"
      @_msgs.UNABLE_TO_FIND_VOLUME = "Can't find find volume {volumeID}"
      @NO_SUCH_ALGORITHM: "NO_SUCH_ALGORITHM"
      @_msgs.NO_SUCH_ALGORITHM = "No such algorithm"
      @UNABLE_TO_RETURN_SOCKET_FACTORY: "UNABLE_TO_RETURN_SOCKET_FACTORY"
      @_msgs.UNABLE_TO_RETURN_SOCKET_FACTORY = "Unable to return SocketFactory"
      @INVALID_PAPI_RESPONSE: "INVALID_PAPI_RESPONSE"
      @_msgs.INVALID_PAPI_RESPONSE = "PAPIResponse is null"
      @INVALID_SIZE_STRING: "INVALID_SIZE_STRING"
      @_msgs.INVALID_SIZE_STRING = "Invalid size format {sizeStr}: must be a number (interpreted as bytes), or a number with one of the following suffixes: kb, mb, gb."
      @UNABLE_TO_CREATE_INVITE: "UNABLE_TO_CREATE_INVITE"
      @_msgs.UNABLE_TO_CREATE_INVITE = "Unable to create invite"
      @MIME_MESSAGE_PARSING_ERROR: "MIME_MESSAGE_PARSING_ERROR"
      @_msgs.MIME_MESSAGE_PARSING_ERROR = "Error parsing MIME message"
      @UNABLE_TO_SET_OUT_OF_OFFICE_SETTINGS: "UNABLE_TO_SET_OUT_OF_OFFICE_SETTINGS"
      @_msgs.UNABLE_TO_SET_OUT_OF_OFFICE_SETTINGS = "Unable to set out of office settings"
      @UNABLE_TO_CALCULATE_SIZE_AND_DIGEST_FOR_ITEM: "UNABLE_TO_CALCULATE_SIZE_AND_DIGEST_FOR_ITEM"
      @_msgs.UNABLE_TO_CALCULATE_SIZE_AND_DIGEST_FOR_ITEM = "Cannot calculate size and digest for item {itemID} - revision {revision} - volume id {volumeID} - mailbox {mboxID}"
      @UNABLE_TO_LOAD_HSM_CONFIGURATION: "UNABLE_TO_LOAD_HSM_CONFIGURATION"
      @_msgs.UNABLE_TO_LOAD_HSM_CONFIGURATION = "Error loading server HSM configuration"
      @INVALID_BLOB_PATH: "INVALID_BLOB_PATH"
      @_msgs.INVALID_BLOB_PATH = "{path} is not a valid blob path"
      @UNKNOWN_LINKING_ERROR: "UNKNOWN_LINKING_ERROR"
      @_msgs.UNKNOWN_LINKING_ERROR = "Unknown Linking Error"
      @ERROR_RETRIEVING_ITEMS_TO_MOVE: "ERROR_RETRIEVING_ITEMS_TO_MOVE"
      @_msgs.ERROR_RETRIEVING_ITEMS_TO_MOVE = "Error retrieving the items to move: {details}"
      @ERROR_RETRIEVING_DATA_FROM_DB: "ERROR_RETRIEVING_DATA_FROM_DB"
      @_msgs.ERROR_RETRIEVING_DATA_FROM_DB = "Error retrieving data from db: {details}"
      @NO_POLICIES_DEFINED: "NO_POLICIES_DEFINED"
      @_msgs.NO_POLICIES_DEFINED = "No policies are been defined"
      @VOLUME_IS_INDEX: "VOLUME_IS_INDEX"
      @_msgs.VOLUME_IS_INDEX = "{volume} is an index volume. Aborting..."
      @ERROR_INITIALIZING_HSM_BLOB_MOVER: "ERROR_INITIALIZING_HSM_BLOB_MOVER"
      @_msgs.ERROR_INITIALIZING_HSM_BLOB_MOVER = "Error initializing HSMBlobMover: {details}"
      @INVALID_HSM_POLICIES: "INVALID_HSM_POLICIES"
      @_msgs.INVALID_HSM_POLICIES = "One or more HSM policies are invalid. Move operation aborted"
      @UNABLE_TO_GET_HSM_POLICIES: "UNABLE_TO_GET_HSM_POLICIES"
      @_msgs.UNABLE_TO_GET_HSM_POLICIES = "Error getting the HSM policy from the local server"
      @MISSING_DEFAULT_INVITE_ON_CALENDAR_ITEM: "MISSING_DEFAULT_INVITE_ON_CALENDAR_ITEM"
      @_msgs.MISSING_DEFAULT_INVITE_ON_CALENDAR_ITEM = "Missing default invite on calendar item: {itemID}"
      @ITEM_TYPE_NOT_YET_HANDLED: "ITEM_TYPE_NOT_YET_HANDLED"
      @_msgs.ITEM_TYPE_NOT_YET_HANDLED = "ZEItem type not yet handled: {type}"
      @UNABLE_TO_SAVE_DEVICE_INFO_ON_DB: "UNABLE_TO_SAVE_DEVICE_INFO_ON_DB"
      @_msgs.UNABLE_TO_SAVE_DEVICE_INFO_ON_DB = "Error saving device informations on DB"
      @UNABLE_TO_READ_DATA_FROM_DB: "UNABLE_TO_READ_DATA_FROM_DB"
      @_msgs.UNABLE_TO_READ_DATA_FROM_DB = "Error reading data from DB"
      @UNABLE_TO_CHANGE_DEVICE_STATUS_ON_DB: "UNABLE_TO_CHANGE_DEVICE_STATUS_ON_DB"
      @_msgs.UNABLE_TO_CHANGE_DEVICE_STATUS_ON_DB = "Error changing device status on DB"
      @UNABLE_TO_CHANGE_DEVICE_PASSWORD_ON_DB: "UNABLE_TO_CHANGE_DEVICE_PASSWORD_ON_DB"
      @_msgs.UNABLE_TO_CHANGE_DEVICE_PASSWORD_ON_DB = "Error changing device password on DB"
      @UNABLE_TO_CHANGE_DEVICE_INFOS_ON_DB: "UNABLE_TO_CHANGE_DEVICE_INFOS_ON_DB"
      @_msgs.UNABLE_TO_CHANGE_DEVICE_INFOS_ON_DB = "Error changing device infos on DB"
      @UNABLE_TO_CREATE_CALENDAR_ITEM: "UNABLE_TO_CREATE_CALENDAR_ITEM"
      @_msgs.UNABLE_TO_CREATE_CALENDAR_ITEM = "Unable to create calendar item"
      @UNABLE_TO_CREATE_SMS_ITEM: "UNABLE_TO_CREATE_SMS_ITEM"
      @_msgs.UNABLE_TO_CREATE_SMS_ITEM = "Unable to create sms item"
      @UNABLE_TO_MODIFY_ITEM: "UNABLE_TO_MODIFY_ITEM"
      @_msgs.UNABLE_TO_MODIFY_ITEM = "Unable to modify item: {id} type: {type}"
      @UNABLE_TO_ADD_DELEGATE: "UNABLE_TO_ADD_DELEGATE"
      @_msgs.UNABLE_TO_ADD_DELEGATE = "Unable to add delegate account."
      @UNABLE_TO_REMOVE_DELEGATED: "UNABLE_TO_REMOVE_DELEGATED"
      @_msgs.UNABLE_TO_REMOVE_DELEGATED = "Unable to remove delegated account."
      @VALUE_ALREADY_SET_ON_NODE: "VALUE_ALREADY_SET_ON_NODE"
      @_msgs.VALUE_ALREADY_SET_ON_NODE = "Value already set on node: {name}"
      @UNABLE_TO_WRITE_VALUE_ON_PARENT_NODE: "UNABLE_TO_WRITE_VALUE_ON_PARENT_NODE"
      @_msgs.UNABLE_TO_WRITE_VALUE_ON_PARENT_NODE = "Unable to write value on parent node: {name}"
      @INVALID_XML_REQUEST: "INVALID_XML_REQUEST"
      @_msgs.INVALID_XML_REQUEST = "Invalid Request XML"
      @UNKNOWN_ERROR_GETTING_RAW_DATA: "UNKNOWN_ERROR_GETTING_RAW_DATA"
      @_msgs.UNKNOWN_ERROR_GETTING_RAW_DATA = "Unknown error getting raw data"
      @INVALID_CALENDAR: "INVALID_CALENDAR"
      @_msgs.INVALID_CALENDAR = "Invalid calendar"
      @UNABLE_TO_SYNC_ITEM: "UNABLE_TO_SYNC_ITEM"
      @_msgs.UNABLE_TO_SYNC_ITEM = "The device is having issues with this item: skipping"
      @FREQUENCY_TYPE_NOT_YET_IMPLEMENTED: "FREQUENCY_TYPE_NOT_YET_IMPLEMENTED"
      @_msgs.FREQUENCY_TYPE_NOT_YET_IMPLEMENTED = "Frequency type {type} not implemented"
      @CALENDAR_EXCEPTION_TYPE_NOT_SUPPORTED: "CALENDAR_EXCEPTION_TYPE_NOT_SUPPORTED"
      @_msgs.CALENDAR_EXCEPTION_TYPE_NOT_SUPPORTED = "Exception type {type} not supported"
      @ACCOUNT_LOCKED: "ACCOUNT_LOCKED"
      @_msgs.ACCOUNT_LOCKED = "Account is Locked"
      @MISSING_ACCOUNT_STATUS: "MISSING_ACCOUNT_STATUS"
      @_msgs.MISSING_ACCOUNT_STATUS = "Missing account status"
      @SERVER_MISCONFIGURATION: "SERVER_MISCONFIGURATION"
      @_msgs.SERVER_MISCONFIGURATION = "Server misconfiguration"
      @UNABLE_TO_FIND_ACCOUNT: "UNABLE_TO_FIND_ACCOUNT"
      @_msgs.UNABLE_TO_FIND_ACCOUNT = "Cannot find account: {account}"
      @UNABLE_TO_FIND_DISTRIBUTION_LIST: "UNABLE_TO_FIND_DISTRIBUTION_LIST"
      @_msgs.UNABLE_TO_FIND_DISTRIBUTION_LIST = "Cannot find distribution list: {distList}"
      @AUTHENTICATION_ERROR: "AUTHENTICATION_ERROR"
      @_msgs.AUTHENTICATION_ERROR = "Authentication error"
      @CONFIRM_NOT_TRUE: "CONFIRM_NOT_TRUE"
      @_msgs.CONFIRM_NOT_TRUE = "Parameter 'confirm' not true. No operation performed"
      @OPERATION_NOT_FOUND: "OPERATION_NOT_FOUND"
      @_msgs.OPERATION_NOT_FOUND = "Operation not found"
      @UNABLE_TO_RETRIEVE_ACCOUNT_RIGHTS: "UNABLE_TO_RETRIEVE_ACCOUNT_RIGHTS"
      @_msgs.UNABLE_TO_RETRIEVE_ACCOUNT_RIGHTS = "Error in retrieving the account's rights."
      @UNABLE_TO_CONNECT_TO_LDAP_SERVER: "UNABLE_TO_CONNECT_TO_LDAP_SERVER"
      @_msgs.UNABLE_TO_CONNECT_TO_LDAP_SERVER = "Cannot connect to the LDAP server {details}"
      @UNABLE_TO_RETRIEVE_DOMAIN_LIST: "UNABLE_TO_RETRIEVE_DOMAIN_LIST"
      @_msgs.UNABLE_TO_RETRIEVE_DOMAIN_LIST = "Error in retrieving domain list"
      @REPORT_NOT_FOUND: "REPORT_NOT_FOUND"
      @_msgs.REPORT_NOT_FOUND = "Report not found"
      @NOT_DELEGATED_ADMIN: "NOT_DELEGATED_ADMIN"
      @_msgs.NOT_DELEGATED_ADMIN = "{account} is not a delegated admin"
      @NO_SUCH_DOMAIN: "NO_SUCH_DOMAIN"
      @_msgs.NO_SUCH_DOMAIN = "No such domain: {domain}"
      @NO_SUCH_GRANT: "NO_SUCH_GRANT"
      @_msgs.NO_SUCH_GRANT = "No such grant: {grant}"
      @HOUR_OUT_OF_RANGE: "HOUR_OUT_OF_RANGE"
      @_msgs.HOUR_OUT_OF_RANGE = "Hour must be in the range [0, 23]"
      @MINUTE_OUT_OF_RANGE: "MINUTE_OUT_OF_RANGE"
      @_msgs.MINUTE_OUT_OF_RANGE = "Minute must be in the range [0, 59]"
      @RETENTION_OUT_OF_RANGE: "RETENTION_OUT_OF_RANGE"
      @_msgs.RETENTION_OUT_OF_RANGE = "Retention must be > 0"
      @UNABLE_TO_SAVE_BACKUP_LOG: "UNABLE_TO_SAVE_BACKUP_LOG"
      @_msgs.UNABLE_TO_SAVE_BACKUP_LOG = "Can't save log backup config file: {path}"
      @INVALID_HOUR: "INVALID_HOUR"
      @_msgs.INVALID_HOUR = "Not a valid hour"
      @INVALID_WEEKDAY: "INVALID_WEEKDAY"
      @_msgs.INVALID_WEEKDAY = "Not a week day"
      @INVALID_SEVERITY_LEVEL: "INVALID_SEVERITY_LEVEL"
      @_msgs.INVALID_SEVERITY_LEVEL = "SeverityLevel not valid"
      @CASE_INSENSITIVE: "CASE_INSENSITIVE"
      @_msgs.CASE_INSENSITIVE = "The ZeXtras Backup's data is being stored in a Case Insensitive filesystem: {path}"
      @INVALID_OPERATION_ON_METADATA: "INVALID_OPERATION_ON_METADATA"
      @_msgs.INVALID_OPERATION_ON_METADATA = "Invalid operation on metadata: {path}"
      @BACKUP_TOO_OLD: "BACKUP_TOO_OLD"
      @_msgs.BACKUP_TOO_OLD = "Backup too old for Trial Version"
      @INVALID_BACKUP_DATE: "INVALID_BACKUP_DATE"
      @_msgs.INVALID_BACKUP_DATE = "Account: {id} doesn't have a valid backup on date '{date}'"
      @RESTORING_ACCOUNT_EXCEPTION: "RESTORING_ACCOUNT_EXCEPTION"
      @_msgs.RESTORING_ACCOUNT_EXCEPTION = "Exception when restoring account informations: {account}"
      @SERVICE_EXCEPTION: "SERVICE_EXCEPTION"
      @_msgs.SERVICE_EXCEPTION = "Service Exception"
      @UNABLE_TO_DELETE_ACCOUNT_ON_ID: "UNABLE_TO_DELETE_ACCOUNT_ON_ID"
      @_msgs.UNABLE_TO_DELETE_ACCOUNT_ON_ID = "Unable to delete id: {id} on account {zid}"
      @MISSING_MID_ATTRIBUTE: "MISSING_MID_ATTRIBUTE"
      @_msgs.MISSING_MID_ATTRIBUTE = "Missing 'mid' attribute in the account metadata"
      @UNABLE_TO_CREATE_DIRECTORY: "UNABLE_TO_CREATE_DIRECTORY"
      @_msgs.UNABLE_TO_CREATE_DIRECTORY = "Unable to create directory: {path}"
      @UNABLE_TO_WRITE_ON_FILE: "UNABLE_TO_WRITE_ON_FILE"
      @_msgs.UNABLE_TO_WRITE_ON_FILE = "Unable to write file: {file}"
      @UNABLE_TO_READ_MAP_FILE: "UNABLE_TO_READ_MAP_FILE"
      @_msgs.UNABLE_TO_READ_MAP_FILE = "Unable to read Map: {file}"
      @STOPPED_BY_USER: "STOPPED_BY_USER"
      @_msgs.STOPPED_BY_USER = "Stopped by user"
      @FREE_SPACE_UNAIVALABLE: "FREE_SPACE_UNAIVALABLE"
      @_msgs.FREE_SPACE_UNAIVALABLE = "Free space is under the threshold. Available Disk Space: {space} MB"
      @UNABLE_TO_WRITE_ON_FOLDER: "UNABLE_TO_WRITE_ON_FOLDER"
      @_msgs.UNABLE_TO_WRITE_ON_FOLDER = "Write permissions missing on backup directory: {folder}"
      @WRONG_SERVER_FOR_LOGGER: "WRONG_SERVER_FOR_LOGGER"
      @_msgs.WRONG_SERVER_FOR_LOGGER = "The account is on server {server}. Add the account logger on that server"
      @UNABLE_TO_ADD_LOGGER_TO_ACCOUNT: "UNABLE_TO_ADD_LOGGER_TO_ACCOUNT"
      @_msgs.UNABLE_TO_ADD_LOGGER_TO_ACCOUNT = "Impossible to add an account logger for account {account}"
      @SERVER_NOT_RUNNING: "SERVER_NOT_RUNNING"
      @_msgs.SERVER_NOT_RUNNING = "Cannot execute command: server is not running!"
      @INVALID_RULE_STRING: "INVALID_RULE_STRING"
      @_msgs.INVALID_RULE_STRING = "Invalid rule string: '{rule}'. Error: {error}"
      @INVALID_EAS_VERSION: "INVALID_EAS_VERSION"
      @_msgs.INVALID_EAS_VERSION = "Invalid eas version: '{version}'. Valid versions: {valid}"
      @INVALID_VALUE_FOR_PARAMETER: "INVALID_VALUE_FOR_PARAMETER"
      @_msgs.INVALID_VALUE_FOR_PARAMETER = "Invalid value '{action}' for parameter command"
      @UNABLE_TO_CHECK_FOR_UPDATES: "UNABLE_TO_CHECK_FOR_UPDATES"
      @_msgs.UNABLE_TO_CHECK_FOR_UPDATES = "Unable to check for updates: {details}"
      @UNABLE_TO_CREATE_VOLUME: "UNABLE_TO_CREATE_VOLUME"
      @_msgs.UNABLE_TO_CREATE_VOLUME = "Error creating volume: {details}"
      @UNABLE_TO_QUEUE_GENERIC_OPERATION_BY_SIMILARITY: "UNABLE_TO_QUEUE_GENERIC_OPERATION_BY_SIMILARITY"
      @_msgs.UNABLE_TO_QUEUE_GENERIC_OPERATION_BY_SIMILARITY = "The selected operation cannot be queued because another similar operation is running or already in the operation queue"
      @UNABLE_TO_QUEUE_OPERATION: "UNABLE_TO_QUEUE_OPERATION"
      @_msgs.UNABLE_TO_QUEUE_OPERATION = "Unable to queue operation {name} from {module}. Cause: {cause}"
      @UNABLE_TO_CLEAR_CHAT_USER_FROM_DB: "UNABLE_TO_CLEAR_CHAT_USER_FROM_DB"
      @_msgs.UNABLE_TO_CLEAR_CHAT_USER_FROM_DB = "Error in clearing user '{user}' from database"
      @UNABLE_TO_DELETE_VOLUME: "UNABLE_TO_DELETE_VOLUME"
      @_msgs.UNABLE_TO_DELETE_VOLUME = "Volume {name} is NOT been deleted."
      @UNABLE_TO_DEPLOY_CHAT_ZIMLET: "UNABLE_TO_DEPLOY_CHAT_ZIMLET"
      @_msgs.UNABLE_TO_DEPLOY_CHAT_ZIMLET = "Unable to deploy ZxChat Zimlet: {details}"
      @UNABLE_TO_ENABLE_DISABLE_ADMIN_LOG: "UNABLE_TO_ENABLE_DISABLE_ADMIN_LOG"
      @_msgs.UNABLE_TO_ENABLE_DISABLE_ADMIN_LOG = "Error enabling/disabling admin log"
      @UNABLE_TO_FIND_COS: "UNABLE_TO_FIND_COS"
      @_msgs.UNABLE_TO_FIND_COS = "Unable to find COS '{name}'"
      @COS_NOT_SAVED: "COS_NOT_SAVED"
      @_msgs.COS_NOT_SAVED = "Please make sure to save the new Class of Service before editing this setting"
      @UNABLE_TO_ENABLE_DISABLE_COS_BACKUP: "UNABLE_TO_ENABLE_DISABLE_COS_BACKUP"
      @_msgs.UNABLE_TO_ENABLE_DISABLE_COS_BACKUP = "Error enabling/disabling COS backup: {details}"
      @INVALID_ACCOUNT_NAME_FORMAT: "INVALID_ACCOUNT_NAME_FORMAT"
      @_msgs.INVALID_ACCOUNT_NAME_FORMAT = "Account name must be in the form name@domain.tld"
      @INVALID_CUSTOM_POLICY: "INVALID_CUSTOM_POLICY"
      @_msgs.INVALID_CUSTOM_POLICY = "The custom policy is not valid"
      @NO_SECONDARY_STORE: "NO_SECONDARY_STORE"
      @_msgs.NO_SECONDARY_STORE = "No secondary store set"
      @UNABLE_TO_DELETE_DEVICE_FROM_SYSTEM: "UNABLE_TO_DELETE_DEVICE_FROM_SYSTEM"
      @_msgs.UNABLE_TO_DELETE_DEVICE_FROM_SYSTEM = "Device NOT deleted from system"
      @UNABLE_TO_SEND_ERROR_REPORT: "UNABLE_TO_SEND_ERROR_REPORT"
      @_msgs.UNABLE_TO_SEND_ERROR_REPORT = "Unable to send error report"
      @STATES_NOT_RESETTED: "STATES_NOT_RESETTED"
      @_msgs.STATES_NOT_RESETTED = "States NOT resetted"
      @ACCOUNT_LIMIT_REACHED_ON_DOMAIN: "ACCOUNT_LIMIT_REACHED_ON_DOMAIN"
      @_msgs.ACCOUNT_LIMIT_REACHED_ON_DOMAIN = "Account limit reached on domain {domain}: {count}"
      @ACCOUNT_LIMIT_REACHED_ON_COS: "ACCOUNT_LIMIT_REACHED_ON_COS"
      @_msgs.ACCOUNT_LIMIT_REACHED_ON_COS = "Account limit reached for COS {cos} on domain {domain}: {count}"
      @ACCOUNT_ALREADY_EXISTS_ON_DOMAIN: "ACCOUNT_ALREADY_EXISTS_ON_DOMAIN"
      @_msgs.ACCOUNT_ALREADY_EXISTS_ON_DOMAIN = "The destination account {account} on domain {domain} already exists"
      @UNABLE_TO_FIND_ACCOUNT_ON_DATE: "UNABLE_TO_FIND_ACCOUNT_ON_DATE"
      @_msgs.UNABLE_TO_FIND_ACCOUNT_ON_DATE = "Account {account} not found on date: {date}"
      @UNABLE_TO_ACCESS_ACCOUNT: "UNABLE_TO_ACCESS_ACCOUNT"
      @_msgs.UNABLE_TO_ACCESS_ACCOUNT = "Could not access the account's mailbox: {account}. Details: {details}"
      @INVALID_MODE: "INVALID_MODE"
      @_msgs.INVALID_MODE = "Invalid mode {mode}"
      @DEPRECATED_HANDLER: "DEPRECATED_HANDLER"
      @_msgs.DEPRECATED_HANDLER = "Deprecated handler"
      @UNABLE_TO_ENCRYPT_PASSWORD: "UNABLE_TO_ENCRYPT_PASSWORD"
      @_msgs.UNABLE_TO_ENCRYPT_PASSWORD = "Could not encrypt the password: {details}"
      @INVALID_EMAIL: "INVALID_EMAIL"
      @_msgs.INVALID_EMAIL = "Invalid email '{part}'"
      @UNABLE_TO_FIND_OPERATION: "UNABLE_TO_FIND_OPERATION"
      @_msgs.UNABLE_TO_FIND_OPERATION = "Operation not found"
      @UNABLE_TO_READ_BACKUP_STATS: "UNABLE_TO_READ_BACKUP_STATS"
      @_msgs.UNABLE_TO_READ_BACKUP_STATS = "{account}'s ZxBackup stats file missing or unreadable"
      @UNABLE_TO_FIND_BACKUP_FOLDER_FOR_ACCOUNT: "UNABLE_TO_FIND_BACKUP_FOLDER_FOR_ACCOUNT"
      @_msgs.UNABLE_TO_FIND_BACKUP_FOLDER_FOR_ACCOUNT = "Can't find the backup folder for the account: {account}."
      @UNABLE_TO_FIND_BACKUP_FILES: "UNABLE_TO_FIND_BACKUP_FILES"
      @_msgs.UNABLE_TO_FIND_BACKUP_FILES = "Server backup files missing"
      @UNABLE_TO_FIND_DOMAIN: "UNABLE_TO_FIND_DOMAIN"
      @_msgs.UNABLE_TO_FIND_DOMAIN = "Could not find domain {domain}"
      @UNABLE_TO_FIND_ACCOUNT_ITEM_IN_PATH: "UNABLE_TO_FIND_ACCOUNT_ITEM_IN_PATH"
      @_msgs.UNABLE_TO_FIND_ACCOUNT_ITEM_IN_PATH = "Can't find item {item} belonging to account {account}.\n       Files {file}\nand    {path} don't exist."
      @INVALID_ITEM_ID: "INVALID_ITEM_ID"
      @_msgs.INVALID_ITEM_ID = "Invalid item id: {item}"
      @UNABLE_TO_FIND_ITEM_STATE_IN_DATE: "UNABLE_TO_FIND_ITEM_STATE_IN_DATE"
      @_msgs.UNABLE_TO_FIND_ITEM_STATE_IN_DATE = "Item {item} of account {account} has no backup state in date {date}. First available date: {firstDate}"
      @UNABLE_TO_FIND_STATE_IN_DATE: "UNABLE_TO_FIND_STATE_IN_DATE"
      @_msgs.UNABLE_TO_FIND_STATE_IN_DATE = "There is no backup available in date {date}. First available date: {firstDate}"
      @OPERATION_NOT_ALREADY_STARTED: "OPERATION_NOT_ALREADY_STARTED"
      @_msgs.OPERATION_NOT_ALREADY_STARTED = "The specified operation has not started yet. To see the ID of the currently running operation,\nexecute the following command: zxsuite backup getAllOperations"
      @OPERATION_FINISHED_OR_STOPPED: "OPERATION_FINISHED_OR_STOPPED"
      @_msgs.OPERATION_FINISHED_OR_STOPPED = "Operation {id} either completed execution or was stopped by the user"
      @INVALID_CUSTOMIZATION_VALUE: "INVALID_CUSTOMIZATION_VALUE"
      @_msgs.INVALID_CUSTOMIZATION_VALUE = "Please specify 'all' or 'last' for the date parameter when using 'customizations'"
      @SERVICE_NOT_FOUND: "SERVICE_NOT_FOUND"
      @_msgs.SERVICE_NOT_FOUND = "Service not found"
      @SERVICE_CANNOT_STOPPED_BY_USER: "SERVICE_CANNOT_STOPPED_BY_USER"
      @_msgs.SERVICE_CANNOT_STOPPED_BY_USER = "This service cannot stopped by user"
      @SERVICE_CONDITIONS_NOT_MET: "SERVICE_CONDITIONS_NOT_MET"
      @_msgs.SERVICE_CONDITIONS_NOT_MET = "Service conditions not met: {reason}"
      @UNABLE_TO_START_MANDATORY_SERVICE: "UNABLE_TO_START_MANDATORY_SERVICE"
      @_msgs.UNABLE_TO_START_MANDATORY_SERVICE = "{message}"
      @UNABLE_TO_START_UNNECESSARY_SERVICE: "UNABLE_TO_START_UNNECESSARY_SERVICE"
      @_msgs.UNABLE_TO_START_UNNECESSARY_SERVICE = "{message}"
      @UNABLE_TO_FIND_NOTIFICATIONS: "UNABLE_TO_FIND_NOTIFICATIONS"
      @_msgs.UNABLE_TO_FIND_NOTIFICATIONS = "Notification not found"
      @UNABLE_TO_REMOVE_FILTER: "UNABLE_TO_REMOVE_FILTER"
      @_msgs.UNABLE_TO_REMOVE_FILTER = "The filter was not removed"
      @UNABLE_TO_RETRIEVE_DELEGATION_SETTINGS: "UNABLE_TO_RETRIEVE_DELEGATION_SETTINGS"
      @_msgs.UNABLE_TO_RETRIEVE_DELEGATION_SETTINGS = "Cannot retrieve delegation settings"
      @TRIVIAL_IO_ERROR: "TRIVIAL_IO_ERROR"
      @_msgs.TRIVIAL_IO_ERROR = "Trivial IO Error: {exception}"
      @ACCOUNT_CONFIG_ERROR: "ACCOUNT_CONFIG_ERROR"
      @_msgs.ACCOUNT_CONFIG_ERROR = "Account configuration error"
      @OPERATION_BLOCKING_ERROR: "OPERATION_BLOCKING_ERROR"
      @_msgs.OPERATION_BLOCKING_ERROR = "Blocking operation error"
      @UNABLE_TO_CREATE_EXPORT_DIRECTORY: "UNABLE_TO_CREATE_EXPORT_DIRECTORY"
      @_msgs.UNABLE_TO_CREATE_EXPORT_DIRECTORY = "Unable to create export directory {path}"
      @UNABLE_TO_CREATE_BACKUP_DIRECTORY: "UNABLE_TO_CREATE_BACKUP_DIRECTORY"
      @_msgs.UNABLE_TO_CREATE_BACKUP_DIRECTORY = "Unable to create backup directory {path}"
      @IO_WRITING_ERROR: "IO_WRITING_ERROR"
      @_msgs.IO_WRITING_ERROR = "I/O Exception in writing content file"
      @UNABLE_TO_DELETE_FILE: "UNABLE_TO_DELETE_FILE"
      @_msgs.UNABLE_TO_DELETE_FILE = "Unable to delete file: {path}, check file permissions"
      @UNABLE_TO_CLONE_BACKUP_STATE: "UNABLE_TO_CLONE_BACKUP_STATE"
      @_msgs.UNABLE_TO_CLONE_BACKUP_STATE = "Unable to clone State"
      @ERROR_SAVING_SERVER_LAYOUT: "ERROR_SAVING_SERVER_LAYOUT"
      @_msgs.ERROR_SAVING_SERVER_LAYOUT = "Exception when saving server layout"
      @ERROR_RESTORING_SERVER_LAYOUT: "ERROR_RESTORING_SERVER_LAYOUT"
      @_msgs.ERROR_RESTORING_SERVER_LAYOUT = "Exception when restoring server layout"
      @POWERSTORE_OPERATION_STOPPED_ON_NE: "POWERSTORE_OPERATION_STOPPED_ON_NE"
      @_msgs.POWERSTORE_OPERATION_STOPPED_ON_NE = "The operation was interrupted because ZxPowerstore must be enabled before being used on Zimbra Network Edition. See http://wiki.zextras.com/wiki/ZxPowerstore:_Hierarchical_Storage_Management#Running_ZxPowerstore_on_Zimbra_Network_Edition for more informations"
      @BACKUP_NOT_INITIALIZED_OP: "BACKUP_NOT_INITIALIZED_OP"
      @_msgs.BACKUP_NOT_INITIALIZED_OP = "Backup not initialized. Please run a Live Smart Scan to initialize the backup system"
      @BACKUP_NOT_INITIALIZED: "BACKUP_NOT_INITIALIZED"
      @_msgs.BACKUP_NOT_INITIALIZED = "Unable to read backup informations: backup is not initialized"
      @MISSING_MOBILE_PARAMETER: "MISSING_MOBILE_PARAMETER"
      @_msgs.MISSING_MOBILE_PARAMETER = "Missing mobile parameter"
      @UNABLE_TO_CREATE_ITEM: "UNABLE_TO_CREATE_ITEM"
      @_msgs.UNABLE_TO_CREATE_ITEM = "Unable to create ZEItem"
      @NEEDED_PROVISIONING_ERROR: "NEEDED_PROVISIONING_ERROR"
      @_msgs.NEEDED_PROVISIONING_ERROR = "Provisioning needed"
      @GENERIC_SHELL_SERVER_ERROR: "GENERIC_SHELL_SERVER_ERROR"
      @_msgs.GENERIC_SHELL_SERVER_ERROR = "Generic Shell Server Error"
      @NON_EXTERNAL_RESTORE_OF_SERVER_CONFIG_NOT_SUPPORTED: "NON_EXTERNAL_RESTORE_OF_SERVER_CONFIG_NOT_SUPPORTED"
      @_msgs.NON_EXTERNAL_RESTORE_OF_SERVER_CONFIG_NOT_SUPPORTED = "Non-External Restore of server configuration not supported yet"
      @UNABLE_TO_CREATE_BACKUP_STATS: "UNABLE_TO_CREATE_BACKUP_STATS"
      @_msgs.UNABLE_TO_CREATE_BACKUP_STATS = "Unable to create backup stats"
      @WRONG_SERVER: "WRONG_SERVER"
      @_msgs.WRONG_SERVER = "Wrong Server"
      @IO_ERROR: "IO_ERROR"
      @_msgs.IO_ERROR = "IO Error"
      @METADATA_OVERSIZE: "METADATA_OVERSIZE"
      @_msgs.METADATA_OVERSIZE = "Metadata Oversize {mboxID} size: {size}"
      @SQL_SCRIPT_ERROR: "SQL_SCRIPT_ERROR"
      @_msgs.SQL_SCRIPT_ERROR = "SQL Script Error"
      @UNABLE_TO_FIND_SQL_SCRIPT: "UNABLE_TO_FIND_SQL_SCRIPT"
      @_msgs.UNABLE_TO_FIND_SQL_SCRIPT = "Cannot find sql script: {path}"
      @UNABLE_TO_READ_SQL_SCRIPT: "UNABLE_TO_READ_SQL_SCRIPT"
      @_msgs.UNABLE_TO_READ_SQL_SCRIPT = "Error reading sql file: {path}"
      @INVALID_MOBILE_COMMAND: "INVALID_MOBILE_COMMAND"
      @_msgs.INVALID_MOBILE_COMMAND = "Invalid command: {command}"
      @INVALID_SYNC_OBJECT: "INVALID_SYNC_OBJECT"
      @_msgs.INVALID_SYNC_OBJECT = "Invalid sync object"
      @EXCEEDING_USER_QUOTA: "EXCEEDING_USER_QUOTA"
      @_msgs.EXCEEDING_USER_QUOTA = "Quota limit of account {account} reached({size} MB)"
      @UNABLE_TO_CHECK_VOLUME: "UNABLE_TO_CHECK_VOLUME"
      @_msgs.UNABLE_TO_CHECK_VOLUME = "Error checking volume {volume}"
      @UNABLE_HANDLE_SERVER_CONFIG: "UNABLE_HANDLE_SERVER_CONFIG"
      @_msgs.UNABLE_HANDLE_SERVER_CONFIG = "ServerConfig not yet handled"
      @MAIL_REJECTED: "MAIL_REJECTED"
      @_msgs.MAIL_REJECTED = "Mail rejected by zimbra validator: {id}"
      @UNABLE_TO_RESTORE_ZEITEM: "UNABLE_TO_RESTORE_ZEITEM"
      @_msgs.UNABLE_TO_RESTORE_ZEITEM = "Unable to restore ZEItem"
      @UNABLE_TO_INITIALIZE_HSM: "UNABLE_TO_INITIALIZE_HSM"
      @_msgs.UNABLE_TO_INITIALIZE_HSM = "HSM Initialization Exception"
      @UNABLE_TO_SCAN_ACCOUNT: "UNABLE_TO_SCAN_ACCOUNT"
      @_msgs.UNABLE_TO_SCAN_ACCOUNT = "Unable to scan account: {account}"
      @DISTRIBUTED_FULL_SCAN_ERROR: "DISTRIBUTED_FULL_SCAN_ERROR"
      @_msgs.DISTRIBUTED_FULL_SCAN_ERROR = "Distribuite Smart Scan Exception"
      @UNABLE_TO_RETRIEVE_ITEMS: "UNABLE_TO_RETRIEVE_ITEMS"
      @_msgs.UNABLE_TO_RETRIEVE_ITEMS = "Error retrieving items"
      @UNABLE_TO_ACCESS_ZIMBRA_FILE: "UNABLE_TO_ACCESS_ZIMBRA_FILE"
      @_msgs.UNABLE_TO_ACCESS_ZIMBRA_FILE = "Unable to access zimbra file: {digest}"
      @INVALID_ZIMBRA_DIGEST: "INVALID_ZIMBRA_DIGEST"
      @_msgs.INVALID_ZIMBRA_DIGEST = "Invalid Zimbra digest: {digest} instead of {realDigest}"
      @UNABLE_TO_INITIALIZE_SHA1_ALGORITHM: "UNABLE_TO_INITIALIZE_SHA1_ALGORITHM"
      @_msgs.UNABLE_TO_INITIALIZE_SHA1_ALGORITHM = "Unable to initialize SHA1 algorithm"
      @UNABLE_TO_COMPLETE_OPERATION: "UNABLE_TO_COMPLETE_OPERATION"
      @_msgs.UNABLE_TO_COMPLETE_OPERATION = "Unable to complete operation {id}. Error(s): {erros}"
      @UNABLE_TO_READ_DIRECTORY: "UNABLE_TO_READ_DIRECTORY"
      @_msgs.UNABLE_TO_READ_DIRECTORY = "Missing read permission for zimbra user on path {path}"
      @BACKUP_PATH_ALREADY_IN_USE: "BACKUP_PATH_ALREADY_IN_USE"
      @_msgs.BACKUP_PATH_ALREADY_IN_USE = "Backup path: {path} is already used by another server, please don't use shared filesystem for backup"
      @INCOMPLETE_BACKUP: "INCOMPLETE_BACKUP"
      @_msgs.INCOMPLETE_BACKUP = "Trying to restore from incomplete backup!"
      @UNABLE_TO_READ_BACKUP_INFO: "UNABLE_TO_READ_BACKUP_INFO"
      @_msgs.UNABLE_TO_READ_BACKUP_INFO = "Unable to read restore backup info"
      @MERGED_MAP_EMPTY: "MERGED_MAP_EMPTY"
      @_msgs.MERGED_MAP_EMPTY = "Merged map is empty, check logs"
      @UNABLE_TO_RETRIEVE_MBOX: "UNABLE_TO_RETRIEVE_MBOX"
      @_msgs.UNABLE_TO_RETRIEVE_MBOX = "Cannot retrieve mailbox"
      @NULL_ITEM_PROCESSED: "NULL_ITEM_PROCESSED"
      @_msgs.NULL_ITEM_PROCESSED = "DoItemScan with a null item!"
      @ITEM_MAPPED_MULTIPLE_TIMES: "ITEM_MAPPED_MULTIPLE_TIMES"
      @_msgs.ITEM_MAPPED_MULTIPLE_TIMES = "Detected Error: id {key} mapped to multiple ids! DO NOT USE maps of failed imports"
      @TOO_MANY_IO_ERRORS: "TOO_MANY_IO_ERRORS"
      @_msgs.TOO_MANY_IO_ERRORS = "This operation has been stopped due to a high number of I/O read errors (> {maxCount}).\nRunning a filesystem check is highly suggested.\nIf you wish to override the number of maximum errors in order to complete the operation, please run the operation through the ZeXtras CLI setting the 'read_error_threshold' parameter to 0.\nLast error message was: '{lastError}'."
      @TOO_MANY_ERRORS: "TOO_MANY_ERRORS"
      @_msgs.TOO_MANY_ERRORS = "This operation has been stopped due to a high number of errors (> {maxCount})."
      @INVALID_JSON_STATE: "INVALID_JSON_STATE"
      @_msgs.INVALID_JSON_STATE = "Invalid JSON State"
      @MISSING_CONFIRMATION_PARAMETER: "MISSING_CONFIRMATION_PARAMETER"
      @_msgs.MISSING_CONFIRMATION_PARAMETER = "The '{parameter}' parameter is false, no action performed"
      @LICENSE_RENEW_ERROR: "LICENSE_RENEW_ERROR"
      @_msgs.LICENSE_RENEW_ERROR = "Error while renewing License"
      @UNABLE_TO_CONTACT_ZEXTRAS_ISP_SERVER: "UNABLE_TO_CONTACT_ZEXTRAS_ISP_SERVER"
      @_msgs.UNABLE_TO_CONTACT_ZEXTRAS_ISP_SERVER = "Unable to contact the ZeXtras server, check networking or contact sales team"
      @UNALBE_TO_AUTHORIZE_ISP_LICENSE: "UNALBE_TO_AUTHORIZE_ISP_LICENSE"
      @_msgs.UNALBE_TO_AUTHORIZE_ISP_LICENSE = "ISP license authorization failed, contact sales team"
      @UNABLE_TO_QUERY_CHAT_DATABASE: "UNABLE_TO_QUERY_CHAT_DATABASE"
      @_msgs.UNABLE_TO_QUERY_CHAT_DATABASE = "Unable to query the chat database: {message}"
      @UNKNOWN_JS_EXCEPTION: "UNKNOWN_JS_EXCEPTION"
      @_msgs.UNKNOWN_JS_EXCEPTION = "JavaScript Exception: {details}"
      @EMPTY_RESPONSE: "EMPTY_RESPONSE"
      @_msgs.EMPTY_RESPONSE = "ZmCsfeException EMPTY_RESPONSE"
      @UNABLE_TO_CREATE_RELATIONSHIP: "UNABLE_TO_CREATE_RELATIONSHIP"
      @_msgs.UNABLE_TO_CREATE_RELATIONSHIP = "Unable to create relationship between {user} and {friend}"
      @USER_CANNOT_PERFORM_ACTION: "USER_CANNOT_PERFORM_ACTION"
      @_msgs.USER_CANNOT_PERFORM_ACTION = "User {user} cannot perform {action}"
      @MODULE_DISABLED: "MODULE_DISABLED"
      @_msgs.MODULE_DISABLED = "Request ignored since module {module} is disabled"
      @MODULE_NOT_RUNNING: "MODULE_NOT_RUNNING"
      @_msgs.MODULE_NOT_RUNNING = "Request ignored since module {module} is not running"
      @ZIMLET_CORE_VERISON_MISMATCH: "ZIMLET_CORE_VERISON_MISMATCH"
      @_msgs.ZIMLET_CORE_VERISON_MISMATCH = "Your ZeXtras zimlet is of a different version from your ZeXtras core"
      @CHAT_DB_EXCEPTION: "CHAT_DB_EXCEPTION"
      @_msgs.CHAT_DB_EXCEPTION = "Chat database error: {message}"
      @CHAT_SQL_EXCEPTION: "CHAT_SQL_EXCEPTION"
      @_msgs.CHAT_SQL_EXCEPTION = "Unable to execute the SQL statement: {sqlStatement}"
      @UNABLE_TO_QUERY_NON_MBOX_SERVERS: "UNABLE_TO_QUERY_NON_MBOX_SERVERS"
      @_msgs.UNABLE_TO_QUERY_NON_MBOX_SERVERS = "Unable to query '{server}', is not a MailBox Server"
      @NO_ENTRY_FOUND_FOR_QUERY: "NO_ENTRY_FOUND_FOR_QUERY"
      @_msgs.NO_ENTRY_FOUND_FOR_QUERY = "No entry found for the query '{query}'"
      @ZIMBRAIM_IMPORT_EXCEPTION: "ZIMBRAIM_IMPORT_EXCEPTION"
      @_msgs.ZIMBRAIM_IMPORT_EXCEPTION = "Unable to complete import of Zimbra IM users: {message}"
      @UNABLE_TO_FIND_LOGGER: "UNABLE_TO_FIND_LOGGER"
      @_msgs.UNABLE_TO_FIND_LOGGER = "Unable to find logger with id {loggerId}."
      @NO_SECONDARY_VOLUME: "NO_SECONDARY_VOLUME"
      @_msgs.NO_SECONDARY_VOLUME = "No secondary message volume is defined."
      @NO_CURRENT_SECONDARY_VOLUME: "NO_CURRENT_SECONDARY_VOLUME"
      @_msgs.NO_CURRENT_SECONDARY_VOLUME = "No secondary message volume marked as current."
      @PATH_DOES_NOT_EXISTS: "PATH_DOES_NOT_EXISTS"
      @_msgs.PATH_DOES_NOT_EXISTS = "Directory {path} doesn't exist"
      @ZIMBRA_ITEM_NOT_FOUND: "ZIMBRA_ITEM_NOT_FOUND"
      @_msgs.ZIMBRA_ITEM_NOT_FOUND = "Items not found in zimbra for mailbox {account}: {itemIds}"
      @ZIMBRA_METADATA_DIFFERENT: "ZIMBRA_METADATA_DIFFERENT"
      @_msgs.ZIMBRA_METADATA_DIFFERENT = "Last backup for {id} is not equal to zimbra {type}"
      @METADATA_DUPLICATED_STATES: "METADATA_DUPLICATED_STATES"
      @_msgs.METADATA_DUPLICATED_STATES = "Backup {type} ( {id} ) contains {numDuplicated} duplicated states."
      @FILE_MARKED_AS_DELETED: "FILE_MARKED_AS_DELETED"
      @_msgs.FILE_MARKED_AS_DELETED = "Item {id} backup file is marked as deleted but its last state is not."
      @CONTENT_NOT_FOUND: "CONTENT_NOT_FOUND"
      @_msgs.CONTENT_NOT_FOUND = "Digest not found: {digest} in date {date} (old {age} days)"
      @CONTENT_NOT_FOUND_WITH_FILE_INFO: "CONTENT_NOT_FOUND_WITH_FILE_INFO"
      @_msgs.CONTENT_NOT_FOUND_WITH_FILE_INFO = "Digest not found in metadata {file}: {digest} in date {date} (old {age} days)"
      @BACKUP_OBJECT_NOT_DELETED: "BACKUP_OBJECT_NOT_DELETED"
      @_msgs.BACKUP_OBJECT_NOT_DELETED = "Last backup state for {id} is not marked as deleted but the {type} doesn't exist in zimbra."
      @BACKUP_OBJECT_IS_DELETED: "BACKUP_OBJECT_IS_DELETED"
      @_msgs.BACKUP_OBJECT_IS_DELETED = "Last backup state for {id} is marked as deleted but the {type} exists in zimbra."
      @NO_STATE_IN_METADATA: "NO_STATE_IN_METADATA"
      @_msgs.NO_STATE_IN_METADATA = "There is no backup available in date {date}. First available date: {first_date}"
      @METADATA_HAS_NO_STATE: "METADATA_HAS_NO_STATE"
      @_msgs.METADATA_HAS_NO_STATE = "Backup {id} doesn't have a valid state"
      @ORPHANED_DIGEST: "ORPHANED_DIGEST"
      @_msgs.ORPHANED_DIGEST = "Backup BLOB file {digest} is not referenced by any metadata in the backup path."
      @METADATA_NOT_ORDERED: "METADATA_NOT_ORDERED"
      @_msgs.METADATA_NOT_ORDERED = "Backup {type} {id} has not ordered states"
      @CHAT_MESSAGE_SIZE_EXCEEDED: "CHAT_MESSAGE_SIZE_EXCEEDED"
      @_msgs.CHAT_MESSAGE_SIZE_EXCEEDED = "The message sent to {target} is {length} long and exceeds {max_size} max permitted size."
      @TYPE_NOT_FOUND_IN_METADATA: "TYPE_NOT_FOUND_IN_METADATA"
      @_msgs.TYPE_NOT_FOUND_IN_METADATA = "Metadata {file} has no type. Affected mailbox: {account}"
      @UNABLE_TO_CHECK_CASE_SENSITIVE: "UNABLE_TO_CHECK_CASE_SENSITIVE"
      @_msgs.UNABLE_TO_CHECK_CASE_SENSITIVE = "Unable to check if filesystem is case sensitive: {error}"
      @INVALID_DAY_RETENTION: "INVALID_DAY_RETENTION"
      @_msgs.INVALID_DAY_RETENTION = "Purge invalid {days} days retention."
      @ACCOUNT_ALREADY_EXISTS: "ACCOUNT_ALREADY_EXISTS"
      @_msgs.ACCOUNT_ALREADY_EXISTS = "The destination account {account} already exists"
      @FIELD_OF_QUOTA_FILE_NOT_EXIST: "FIELD_OF_QUOTA_FILE_NOT_EXIST"
      @_msgs.FIELD_OF_QUOTA_FILE_NOT_EXIST = "The field {name} doesn't exist in {type} quota file."
      @REMOTE_AUTHENTICATION_FAILED: "REMOTE_AUTHENTICATION_FAILED"
      @_msgs.REMOTE_AUTHENTICATION_FAILED = "Unable to remote authenticate account {account}"
      @UNABLE_TO_DECODE_SYNCSTATE: "UNABLE_TO_DECODE_SYNCSTATE"
      @_msgs.UNABLE_TO_DECODE_SYNCSTATE = "Unable to decode sync state"
      @UNABLE_TO_FIND_SYNCSTATE: "UNABLE_TO_FIND_SYNCSTATE"
      @_msgs.UNABLE_TO_FIND_SYNCSTATE = "Unable to find sync state {synckey}"
      @NO_CHANGES_SPECIFIED: "NO_CHANGES_SPECIFIED"
      @_msgs.NO_CHANGES_SPECIFIED = "No changes have been specified"
      @INVALID_QUOTA_STRING: "INVALID_QUOTA_STRING"
      @_msgs.INVALID_QUOTA_STRING = "Invalid quota string"
      @PERMISSION_DENIED: "PERMISSION_DENIED"
      @_msgs.PERMISSION_DENIED = "Your user doesn't have the required privileges to perform this action"
      @BLOB_NOT_FOUND: "BLOB_NOT_FOUND"
      @_msgs.BLOB_NOT_FOUND = "Blob not found for item {id}: {file}"
      @CORRUPTED_BACKUP_FILE: "CORRUPTED_BACKUP_FILE"
      @_msgs.CORRUPTED_BACKUP_FILE = "Backup file {file} is corrupted. Affected mailbox: {account}"
      @CORRUPTED_BACKUP_FILE_TRY_FIX: "CORRUPTED_BACKUP_FILE_TRY_FIX"
      @_msgs.CORRUPTED_BACKUP_FILE_TRY_FIX = "Backup file {file} was corrupted and has been overwritten. Affected mailbox: {account}"
      @BACKUP_FILE_DOES_NOT_EXIST: "BACKUP_FILE_DOES_NOT_EXIST"
      @_msgs.BACKUP_FILE_DOES_NOT_EXIST = "Cannot access backup file {file}. Affected mailbox: {account}"
      @BACKUP_FILE_DOES_NOT_EXIST_TRY_FIX: "BACKUP_FILE_DOES_NOT_EXIST_TRY_FIX"
      @_msgs.BACKUP_FILE_DOES_NOT_EXIST_TRY_FIX = "Unreadable backup file {file} has been overwritten. Affected mailbox: {account}"
      @INVALID_SYNC_KEY: "INVALID_SYNC_KEY"
      @_msgs.INVALID_SYNC_KEY = "Invalid format of synchronization key: {key}"
      @MISSING_READ_PERMISSIONS: "MISSING_READ_PERMISSIONS"
      @_msgs.MISSING_READ_PERMISSIONS = "Missing read permissions on {path}"
      @MISSING_WRITE_PERMISSIONS: "MISSING_WRITE_PERMISSIONS"
      @_msgs.MISSING_WRITE_PERMISSIONS = "Missing write permissions on {path}"
      @MISSING_EXECUTE_PERMISSIONS: "MISSING_EXECUTE_PERMISSIONS"
      @_msgs.MISSING_EXECUTE_PERMISSIONS = "Missing execute permissions on {path}"
      @EMPTY_BACKUP_ACCOUNT: "EMPTY_BACKUP_ACCOUNT"
      @_msgs.EMPTY_BACKUP_ACCOUNT = "Backup directory for account {account} is empty."
      @PARENT_NOT_FOUND_IN_BACKUP: "PARENT_NOT_FOUND_IN_BACKUP"
      @_msgs.PARENT_NOT_FOUND_IN_BACKUP = "Cannot find folder {parentId} in backup for item {id}. Affected mailbox: {account}"
      @INVALID_BACKUP_PATH: "INVALID_BACKUP_PATH"
      @_msgs.INVALID_BACKUP_PATH = "Path '{path}' is not a valid backup path."
      @INVALID_BACKUP_FILE: "INVALID_BACKUP_FILE"
      @_msgs.INVALID_BACKUP_FILE = "Cannot handle backup file '{path}'"
      @INVALID_BACKUP_RETENTION_DAYS: "INVALID_BACKUP_RETENTION_DAYS"
      @_msgs.INVALID_BACKUP_RETENTION_DAYS = "Retention days must be a positive number."
      @BACKUP_ITEM_TYPE_IS_NOT_FOLDER: "BACKUP_ITEM_TYPE_IS_NOT_FOLDER"
      @_msgs.BACKUP_ITEM_TYPE_IS_NOT_FOLDER = "Backup item {id} type is not Folder. Affected mailbox: {account}"
      @UNABLE_TO_PARSE_EVENT_OBJECT: "UNABLE_TO_PARSE_EVENT_OBJECT"
      @_msgs.UNABLE_TO_PARSE_EVENT_OBJECT = "Unable to parse the event object:\n{object}"
      @UNABLE_TO_HANDLE_EVENT_HANDLER_NOT_SET: "UNABLE_TO_HANDLE_EVENT_HANDLER_NOT_SET"
      @_msgs.UNABLE_TO_HANDLE_EVENT_HANDLER_NOT_SET = "Handler for event '{code}' not set."
      @UNABLE_TO_REMOVE_DEFAULT_GROUP: "UNABLE_TO_REMOVE_DEFAULT_GROUP"
      @_msgs.UNABLE_TO_REMOVE_DEFAULT_GROUP = "Unable to remove the default group"
      @UNABLE_TO_ADD_USER_AS_BUDDY_HIMSELF: "UNABLE_TO_ADD_USER_AS_BUDDY_HIMSELF"
      @_msgs.UNABLE_TO_ADD_USER_AS_BUDDY_HIMSELF = "User cannot add himself/herself as buddy"
      @UNABLE_TO_SET_SHARED_SYNC_ATTRIBUTE: "UNABLE_TO_SET_SHARED_SYNC_ATTRIBUTE"
      @_msgs.UNABLE_TO_SET_SHARED_SYNC_ATTRIBUTE = "Unable to set shared sync attribute"

      @getMessage: (code) -> if ZxErrorCode._msgs[code]? then ZxErrorCode._msgs[code] else code

    exports.ZxErrorCode = ZxErrorCode
    if window? then window.ZxErrorCode = ZxErrorCode
    return
)
